name: synthecure
description: A new Flutter project.

publish_to: 'none'
version: 2.0.0

environment:
  sdk: '^3.5.0'

dependencies:
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_ui_firestore: ^1.2.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  flutter_svg: ^2.0.2
  go_router: ^14.6.3
  intl: ^0.19.0
  rxdart: ^0.28.0
  shared_preferences: ^2.0.18
  introduction_screen: ^3.1.9
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0
  riverpod_annotation: ^2.1.1
  signature: ^5.3.2
  screenshot: ^3.0.0
  url_launcher: ^6.1.10
  flutter_barcode_scanner: ^2.0.0
  path_provider: ^2.0.15
  flutter_slidable: ^3.1.0
  cart_stepper: ^4.1.1
  mailer: ^6.0.1
  http: ^1.1.0
  flutter_easyloading: ^3.0.5
  flutter_email_sender: ^6.0.2
  google_fonts: ^6.2.1
  lottie: ^3.0.0
  expansion_tile_group: ^2.2.0
  cupertino_modal_sheet: ^1.1.0
  cupertino_onboarding: ^1.2.0
  super_cupertino_navigation_bar: ^2.1.2
  cloud_functions: ^5.3.1
  fl_chart: ^0.63.0  # Check for latest version
  easy_pie_chart: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  random_string: ^2.3.1
  flutter_lints: ^5.0.0
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.14.2
  # the code generator
  riverpod_generator: ^2.2.3
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: ^2.3.10
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: ^0.7.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#ADD8E6"
    theme_color: "#ADD8E6"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"

# https://stackoverflow.com/a/74234079/436422
#dependency_overrides:
#  firebase_core_platform_interface: 4.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/syn_home.png
    - assets/Synthecure_Logo.jpg
    - assets/background.png
    - assets/avatar.png
    - assets/avatar2.png
    - assets/brochure_1.png
    - assets/brochure_2.png
    - assets/brochure_3.png
    - assets/synthecure_logo.png
    - assets/synthecure-logo.jpg
    - assets/synthecure-main.png
    - assets/avatar_anim.json


  
